[project]
site_name = "[[ cookiecutter.project_slug ]]"
site_description = "[[ cookiecutter.description ]]"
repo_url = "https://github.com/andrewasheridan/[[ cookiecutter.github_repo ]]"
repo_name = "andrewasheridan/[[ cookiecutter.github_repo ]]"
docs_dir = "docs"
site_dir = "site"
nav = [
  {"Home" = "index.md"},
]

[project.theme]
variant = "classic"

[project.plugins.search]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
show_root_heading = true
members_order = "source"
